# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PeopleLink' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PeopleLink
  pod 'Firebase/Core'

  pod 'Firebase/Messaging'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

end
